import {
  inter,
  roboto,
  open_sans,
  lato,
  poppins,
  nunito,
  dm_sans,
  manrope,
  work_sans,
  jetbrains_mono,
  ibm_plex_mono,
  space_mono,
  fira_code,
  source_code_pro,
  sora,
  syne,
  bricolage_grotesque,
  instrument_serif,
  waiting_for_the_sunrise,
} from "~/components/common/fonts/fonts";

export const fontNames = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Poppins",
  "Nunito",
  "DM Sans",
  "Manrope",
  "Work Sans",
  "JetBrains Mono",
  "IBM Plex Mono",
  "Space Mono",
  "Fira Code",
  "Source Code Pro",
  "Sora",
  "Syne",
  "Bricolage Grotesque",
  "Instrument Serif",
  "Waiting for the Sunrise",
];


export const fontMap: Record<string, string> = {
  "Inter": inter.className,
  "Roboto": roboto.className,
  "Open Sans": open_sans.className,
  "Lato": lato.className,
  "Poppins": poppins.className,
  "Nunito": nunito.className,
  "DM Sans": dm_sans.className,
  "Manrope": manrope.className,
  "Work Sans": work_sans.className,
  "JetBrains Mono": jetbrains_mono.className,
  "IBM Plex Mono": ibm_plex_mono.className,
  "Space Mono": space_mono.className,
  "Fira Code": fira_code.className,
  "Source Code Pro": source_code_pro.className,
  "Sora": sora.className,
  "Syne": syne.className,
  "Bricolage Grotesque": bricolage_grotesque.className,
  "Instrument Serif": instrument_serif.className,
  "Waiting for the Sunrise": waiting_for_the_sunrise.className,
};
